### ISSUE TITLE
/usr/python not found after Monterey 12.3 update

### ISSUE THREAD

**Issue by Alvt5** [gohoyer/Alfred-Rectangle-Shortcuts#3]
After update this week to 12.3, the workflow has this error "Unable to Run
Reason: launch path not accessible

/usr/bin/python

Check that the selected language exists on your system."

I understand that python 2 is removed as of 12.3 Monterey. 

Any update or suggested solution to this?

Thanks

**Comment by gohoyer** [comment]
I`ve converted the script filter to a external script and added a Requirements section on README.md.

After you install python3 on your system, could you test the [release v1.2.0](https://github.com/gohoyer/Alfred-Rectangle-Shortcuts/releases/tag/1.2.0) to check if it solved your problem?
